### ISSUE TITLE
Upgrade to `v0.17.71` is impossible due to missing context in generated code

### ISSUE THREAD

**Issue by darkweak** [99designs/gqlgen#3688]
Hello there,

I'm using gqlgen for a while but I cannot upgrade to `v0.17.71` or  `v0.17.72` due to the following error message when running `go generate ./...`

```
cannot use &executableSchema{…} (value of type *executableSchema) as graphql.ExecutableSchema value in return statement: *executableSchema does not implement graphql.ExecutableSchema (wrong type for method Complexity)
                have Complexity(string, string, int, map[string]any) (int, bool)
                want Complexity(context.Context, string, string, int, map[string]any) (int, bool)
```

It works well on `v0.17.70`.  
I saw this PR https://github.com/99designs/gqlgen/pull/3630 has been merged to pass the context but it seems the generated code doesn't implement it.

Is there some changes about the configuration that I probably missed?

Thank you for your great work and your time to answer to this issue.

**Comment by git-hulk** [comment]
@darkweak Did you also update your `gqlgen` to `v0.17.72` in your go.mod?

**Comment by darkweak** [comment]
Yep, I tried to upgrade `github.com/99designs/gqlgen` to `v0.17.72` but it throws this error.

**Comment by git-hulk** [comment]
> Yep, I tried to upgrade `github.com/99designs/gqlgen` to `v0.17.72` but it throws this error.

hmmm, seems you're using the older version of gqlgen when generating. You could run `gqlgen -v` on your side to see if it matches the version in your go.mod.

**Comment by darkweak** [comment]
You were right, I missed a place that it was used, I'm so dumb:
```
//go:generate go run github.com/99designs/gqlgen@v0.17.66
```

Thank you for your time, I'm closing this issue. 🙂
